version: '3.8'

services:
  web:
    build: .
    command: gunicorn yalla_business_api.wsgi:application --bind 0.0.0.0:8001 --workers 4
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    


