# Generated by Django 3.1.2 on 2020-10-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_pic', models.TextField()),
                ('store_name', models.CharField(max_length=64)),
                ('review_rank', models.IntegerField()),
                ('openning_time', models.CharField(max_length=64)),
                ('price_range', models.CharField(max_length=64)),
                ('images', models.TextField()),
                ('store_location', models.CharField(max_length=64)),
            ],
        ),
    ]
