# Generated by Django 3.1.2 on 2020-10-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yalla_business_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
