# Generated by Django 3.1.2 on 2020-10-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yalla_business_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
