# Generated by Django 3.1.2 on 2020-10-14 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yalla_business_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_pic', models.TextField()),
                ('store_name', models.CharField(max_length=64)),
                ('review_rank', models.IntegerField()),
                ('opening_times', models.CharField(max_length=64)),
                ('price_range', models.CharField(max_length=64)),
                ('images', models.TextField()),
                ('store_location', models.CharField(max_length=64)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
