# Generated by Django 3.1.2 on 2020-10-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yalla_business_app', '0003_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_profile',
            new_name='UserProfile',
        ),
    ]
