# Generated by Django 3.1.2 on 2020-10-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yalla_business_app', '0003_store_catagories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='catagories',
            field=models.CharField(choices=[('Resturant', 'Resturant'), ('Clothes', 'Clothes'), ('Services', 'Services'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Electrical', 'Electrical')], default='Education', max_length=20),
        ),
    ]
