# Generated by Django 3.1.2 on 2020-10-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yalla_business_app', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='store_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yalla_business_app.store'),
        ),
    ]
